- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"

- platform: integration
  source: sensor.zonneplan_p1_electricity_production
  name: electricity_production
  unit_prefix: k
  round: 2

- platform: statistics
  name: "Max Zonneplan P1 Electricity Average"
  entity_id: sensor.zonneplan_p1_electricity_average
  state_characteristic: value_max
  max_age:
    days: 365

- platform: statistics
  name: "Min Zonneplan P1 Electricity Average"
  entity_id: sensor.zonneplan_p1_electricity_average
  state_characteristic: value_min
  max_age:
    days: 365

- platform: mqtt_room
  device_id: "iphone_van_bram"
  name: "iPhone van Bram kamer"
  state_topic: "espresense/devices/phone:iphone-bram"
  timeout: 10
  away_timeout: 120
  unique_id: C34C16E1-2B2D-46DB-A89F-0DF0556B451E

- platform: mqtt_room
  device_id: "apple_watch_van_bram"
  name: "Apple Watch van Bram"
  state_topic: "espresense/devices/apple_watch_van_bram"
  timeout: 10
  away_timeout: 120
